name: Deploy terraform init & plan . reusable

on:
  workflow_call:
    # inputs:
    #   awsRegion:
    #     required: true
    #     type: string
    secrets:
      ACCESS_KEY_AWS:
        required: true

      SECRET_KEY_AWS:
        required: true

jobs:
  plan:
    runs-on: ubuntu-latest
    outputs:
      PLAN_FILE: ${{ steps.terraform_plan.outputs.plan_file }}

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_AWS }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY_AWS }}
          aws-region: eu-west-3 #${{inputs.awsRegion}}

      - name: Terraform Init
        run: terraform init

      - name: Run Terraform Plan
        id: terraform_plan
        run: |
          terraform plan -out=tfplan
          plan_file=$(cat tfplan) >> $GITHUB_OUTPUT
          echo "$(terraform plan -no-color)" >> $GITHUB_STEP_SUMMARY
